In [102]:
import numpy as np
import pandas as pd

# Task 1

In [103]:
transition_matrix = np.array([
    [0, 1, 1],
    [0, 0, 1],
    [0, 1, 0]
])
teleportation_coef = 0.1

prob_matrix = transition_matrix / np.sum(transition_matrix, axis=1)[:, None]
prob_matrix *= np.array([1 - teleportation_coef] * 3)
prob_matrix += np.array([teleportation_coef / 3] * 3)

page_rank = np.array([1 / 3] * 3)

prev_page_rank = np.ones(shape=(3))
epsilon = 1e-10
iteration = 0
while np.all(prev_page_rank - page_rank) > epsilon:
    iteration += 1
    prev_page_rank = page_rank
    page_rank = np.dot(page_rank, prob_matrix)
print('page rank converged after iteration', iteration)
print('\ntransition matrix\n', transition_matrix)
print('\nprobability matrix\n', prob_matrix)
print('\npage rank\n', page_rank)

page rank converged after iteration 2

transition matrix
 [[0 1 1]
 [0 0 1]
 [0 1 0]]

probability matrix
 [[0.03333333 0.48333333 0.48333333]
 [0.03333333 0.03333333 0.93333333]
 [0.03333333 0.93333333 0.03333333]]

page rank
 [0.03333333 0.48333333 0.48333333]


# Task 2

In [104]:
nodes = ['Home', 'About', 'Product', 'Links', 'EsA', 'EsB', 'EsC', 'EsD']
transition_matrix = pd.DataFrame(np.zeros((8,8)).astype(int), columns=nodes, index=nodes)
transition_matrix.loc['Home'][['About', 'Product', 'Links']] = 1
transition_matrix.loc['About'][['Home']] = 1
transition_matrix.loc['Product'][['Home']] = 1
transition_matrix.loc['Links'][['Home', 'EsA']] = 1
transition_matrix.loc['Links'][['Home', 'EsB']] = 1
transition_matrix.loc['Links'][['Home', 'EsC']] = 1
transition_matrix.loc['Links'][['Home', 'EsD']] = 1
transition_matrix

Home  About  Product  Links  EsA  EsB  EsC  EsD
Home        0      1        1      1    0    0    0    0
About       1      0        0      0    0    0    0    0
Product     1      0        0      0    0    0    0    0
Links       1      0        0      0    1    1    1    1
EsA         0      0        0      0    0    0    0    0
EsB         0      0        0      0    0    0    0    0
EsC         0      0        0      0    0    0    0    0
EsD         0      0        0      0    0    0    0    0

In [105]:
prob_matrix = np.array(transition_matrix)
prob_matrix = prob_matrix / np.sum(prob_matrix, axis=1)[:, None]
prob_matrix *= np.array([1 - teleportation_coef] * 8)
prob_matrix += np.array([teleportation_coef / 8] * 8)
prob_matrix[-4:, :] = 1 / 8
prob_matrix

C:\tools\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([[0.0125, 0.3125, 0.3125, 0.3125, 0.0125, 0.0125, 0.0125, 0.0125],
       [0.9125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125],
       [0.9125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125],
       [0.1925, 0.0125, 0.0125, 0.0125, 0.1925, 0.1925, 0.1925, 0.1925],
       [0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 ],
       [0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 ],
       [0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 ],
       [0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 , 0.125 ]])

In [106]:
page_rank = np.array([1 / 8] * 8)

prev_page_rank = np.ones(shape=(8))
epsilon = 1e-10
iteration = 0
while np.all(prev_page_rank - page_rank) > epsilon:
    iteration += 1
    prev_page_rank = page_rank
    page_rank = np.dot(page_rank, prob_matrix)
print('page rank converged after iteration', iteration)
print('\ntransition matrix\n', transition_matrix)
print('\nprobability matrix\n', prob_matrix)
print('\npage rank\n', page_rank)

page rank converged after iteration 147

transition matrix
          Home  About  Product  Links  EsA  EsB  EsC  EsD
Home        0      1        1      1    0    0    0    0
About       1      0        0      0    0    0    0    0
Product     1      0        0      0    0    0    0    0
Links       1      0        0      0    1    1    1    1
EsA         0      0        0      0    0    0    0    0
EsB         0      0        0      0    0    0    0    0
EsC         0      0        0      0    0    0    0    0
EsD         0      0        0      0    0    0    0    0

probability matrix
 [[0.0125 0.3125 0.3125 0.3125 0.0125 0.0125 0.0125 0.0125]
 [0.9125 0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.0125]
 [0.9125 0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.0125]
 [0.1925 0.0125 0.0125 0.0125 0.1925 0.1925 0.1925 0.1925]
 [0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.125 ]
 [0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.125 ]
 [0.125  0.125  0.125  0.125  0.125  0.125  0.125  0